# Generated by Django 2.2.6 on 2019-10-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0008_logentry_timestamp_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'create'), (1, 'update'), (2, 'delete')], db_index=True, verbose_name='action'),
        ),
    ]
